### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by danklein10** [joshmarshall/jsonrpclib#38]
Is there a plan to add support for python 3? 

It looks like there only should be slight modifications for that (such as handling import of xmlrpclib).

**Comment by advornic** [comment]
+1

**Comment by chiesax** [comment]
then why not just do it? I think in the spirit of python3 should be renamed to jsonrpc. This will also avoid confusions.

**Comment by chiesax** [comment]
after some tentatives with python3, I don't think its just a small matter. Requires some effort, as the api of urllib has changed.

**Comment by chiesax** [comment]
somebody already did it! See tcalmant/jsonrpclib... its called jsonrpclib-pelix. Have not tested yet.

**Comment by danklein10** [comment]
I have tested jsonrpclib-pelix with both Python 2 and 3 from the client side and Python 2 on the server side. 
Overall, I found it stable and on top of Python 3 itself it offers some more features which might be useful, for example raising an app error instead of protocol error in case of an error raised by the server by the user.

**Comment by iten123** [comment]
+1, my project requires jsonrpclib's Python 3 support. Is there any plan doing this or encourage us to use jsonrpclib-pelix?

**Comment by chiesax** [comment]
We should probably ask to @joshmarshall...

**Comment by collinanderson** [comment]
See here for part of the holdup: https://github.com/joshmarshall/jsonrpclib/pull/39#issuecomment-140971881

**Comment by joshmarshall** [comment]
Should be addressed in 0.2.1
